### PR TITLE
[INTERNAL] Allow intra-broker goals to be used as default

### PR DESCRIPTION
**Pull request by alexander-falca**
This PR resolves https://github.com/linkedin/cruise-control/issues/1264 

It seems that intra.broker.goals setting is checked at config validation only and this PR updates sanity check logic. 

Adding WIP label while testing in dev env.

### CODE REVIEW

**Comment by amuraru** [comment]
@alexander-falca I am not sure if this is enough to implement linkedin#1264

The need for us is to have the intra-broker goals available in self.healer. Meaning that similarly to the other _inter_ brokers goals we'd need the healer to continously analyze these intra-broker goals and self-heal them automatically.
CC maintainers suggested we could have a second healer - one dedicated for these goals - that can run in parallel with the current one.

**Comment by ecojan** [comment]
Small things to mention:

- topic.config.provider has changed default value and `com.linkedin.kafka.cruisecontrol.config.KafkaAdminTopicConfigProvider` does not exist anymore
- min.topic.leaders.per.broker has a minimum of 1 now (-1 is not allowed)

Goals seem to be added successfully to the list of goals for self-healing, in the UI, the proposals tab has a generic table that doesn't do any justice to the intra-broker goals.

**Comment by ecojan** [comment]
Found the following error in logs

```
[2021-10-07 09:27:23,902] ERROR Uncaught exception in anomaly handler. (com.linkedin.kafka.cruisecontrol.detector.AnomalyDetectorManager)
com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.IllegalArgumentException: IntraBrokerDiskCapacityGoal does not support balancing action not specifying logdir.
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.computeResult(GoalBasedOperationRunnable.java:167) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.RebalanceRunnable.workWithoutClusterModel(RebalanceRunnable.java:115) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.computeResult(GoalBasedOperationRunnable.java:173) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.detector.GoalViolations.fix(GoalViolations.java:89) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.detector.AnomalyDetectorManager$AnomalyHandlerTask.fixAnomalyInProgress(AnomalyDetectorManager.java:547) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.detector.AnomalyDetectorManager$AnomalyHandlerTask.processAnomalyInProgress(AnomalyDetectorManager.java:413) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.detector.AnomalyDetectorManager$AnomalyHandlerTask.handleAnomalyInProgress(AnomalyDetectorManager.java:396) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.detector.AnomalyDetectorManager$AnomalyHandlerTask.run(AnomalyDetectorManager.java:358) [cruise-control.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: IntraBrokerDiskCapacityGoal does not support balancing action not specifying logdir.
	at com.linkedin.kafka.cruisecontrol.analyzer.goals.IntraBrokerDiskCapacityGoal.actionAcceptance(IntraBrokerDiskCapacityGoal.java:129) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.analyzer.AnalyzerUtils.isProposalAcceptableForOptimizedGoals(AnalyzerUtils.java:121) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.analyzer.goals.AbstractGoal.maybeApplyBalancingAction(AbstractGoal.java:254) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.analyzer.goals.MinTopicLeadersPerBrokerGoal.maybeMoveLeaderOfTopicToBroker(MinTopicLeadersPerBrokerGoal.java:340) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.analyzer.goals.MinTopicLeadersPerBrokerGoal.rebalanceForBroker(MinTopicLeadersPerBrokerGoal.java:316) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.analyzer.goals.AbstractGoal.optimize(AbstractGoal.java:100) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer.optimizations(GoalOptimizer.java:447) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.optimizations(KafkaCruiseControl.java:583) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.ProposalsRunnable.workWithClusterModel(ProposalsRunnable.java:114) ~[cruise-control.jar:?]
	at com.linkedin.kafka.cruisecontrol.servlet.handler.async.runnable.GoalBasedOperationRunnable.computeResult(GoalBasedOperationRunnable.java:161) ~[cruise-control.jar:?]
	... 13 more
```

**Comment by ecojan** [comment]
Does the same for "IntraBrokerDiskUsageDistributionGoal" as well.

**Comment by alexander-falca** [comment]
Closing in favour of https://github.com/linkedin/cruise-control/pull/1721

**Pull request closed without merging**
